#!/usr/bin/python3

try:
  print(x)
except:
  print("An exception occurred")
